
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "luhnChecksum", targetNamespace = "http://ws/", className = "ws.LuhnChecksum")
    @ResponseWrapper(localName = "luhnChecksumResponse", targetNamespace = "http://ws/", className = "ws.LuhnChecksumResponse")
    @Action(input = "http://ws/MyWebService/luhnChecksumRequest", output = "http://ws/MyWebService/luhnChecksumResponse")
    public boolean luhnChecksum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isPalindrome", targetNamespace = "http://ws/", className = "ws.IsPalindrome")
    @ResponseWrapper(localName = "isPalindromeResponse", targetNamespace = "http://ws/", className = "ws.IsPalindromeResponse")
    @Action(input = "http://ws/MyWebService/isPalindromeRequest", output = "http://ws/MyWebService/isPalindromeResponse")
    public boolean isPalindrome(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Double>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "quadraticEquationSolve", targetNamespace = "http://ws/", className = "ws.QuadraticEquationSolve")
    @ResponseWrapper(localName = "quadraticEquationSolveResponse", targetNamespace = "http://ws/", className = "ws.QuadraticEquationSolveResponse")
    @Action(input = "http://ws/MyWebService/quadraticEquationSolveRequest", output = "http://ws/MyWebService/quadraticEquationSolveResponse")
    public List<Double> quadraticEquationSolve(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
